language: python
python:
- 2.7
- 3.5
- pypy

install:
- pip install \
    `python -c 'from setup import META; print(" ".join(META["extras_require"]["testing"] + META["install_requires"]))'`
- pip install coveralls
- python setup.py develop

script:
- make clean
- coverage run --source=markdown_checklist setup.py test
- coverage report -m

after_success: coveralls
